version: '2'
services:
  atrix:
    build:
      context: .
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    image: trigo/atrix:latest
    command: 'yarn run test'
    environment:
      - MONGO_SRV=mongodb://mongo
      - NODE_ENV=test
      - NPM_TOKEN
    networks:
      - atrix_test
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - atrix_test

networks:
  atrix_test:
    driver: bridge
